name: Terraform Plan Difference
on:
  pull_request:
    branches:
      - master



jobs:
  precheck:
    runs-on: ubuntu-latest
    outputs:
      exists: ${{ steps.dircheck.outputs.exists }}
    steps:
      - uses: actions/checkout@v4
      - id: dircheck
        run: |
          # Set true if the directory exists (and has at least one file); else false
          if [ -d "examples/complete" ] && [ "$(ls -A examples/complete 2>/dev/null)" ]; then
            echo "exists=true" >> "$GITHUB_OUTPUT"
          else
            echo "exists=false" >> "$GITHUB_OUTPUT"
          fi

  complete-example:
    needs: precheck
    # Allow workflow to run regardless of examples/complete existence
    if: always()
    uses: clouddrove/github-shared-workflows/.github/workflows/tf-pr-checks.yaml@master
    with:
      provider: 'azurerm'
      terraform_directory: 'examples/complete'
      target_branch: 'master'
    secrets:
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}